service: medical-appointment

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    MYSQL_HOST: ${env:RDS_HOST}
    MYSQL_USER: ${env:RDS_USER}
    MYSQL_PASSWORD: ${env:RDS_PASSWORD}
    MYSQL_DATABASE: ${env:RDS_DATABASE}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    SNS_ARN_PE: ${env:SNS_ARN_PE}
    SNS_ARN_CL: ${env:SNS_ARN_CL}
    SQS_ARN_PE: ${env:SQS_ARN_PE}
    SQS_ARN_CL: ${env:SQS_ARN_CL}
    SQS_URLPE: ${env:SQS_URLPE}
    SQS_URLCL: ${env:SQS_URLCL}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:CreateTopic
        - sns:Subscribe
        - sns:ListSubscriptions
        - sns:ListSubscriptionsByTopic
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - !GetAtt SQSPE.Arn
        - !GetAtt SQSCL.Arn
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - rds:DescribeDBInstances
        - rds:Connect
      Resource: "*"

functions:
  appointment:
    handler: src/lambdas/appointment.handler
    events:
      - http:
          path: appointments
          method: post
      - http:
          path: appointments/{insuredId}
          method: get
      - sqs:
          arn:
            Fn::GetAtt: [ConfirmationsQueue, Arn]
          batchSize: 5

  appointmentPE:
    handler: src/lambdas/appointmentPE.appointmentPE
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSPE, Arn]
          batchSize: 5

  appointmentCL:
    handler: src/lambdas/appointmentCL.appointmentCL
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSCL, Arn]
          batchSize: 5

resources:
  Resources:

    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointments
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    SNSPE:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNSPE

    SNSCL:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SNSCL

    SQSPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQSPE

    SQSCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQSCL

    ConfirmationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment_confirmations

    SNSSubscriptionPE:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref SNSPE  # Utilizando la referencia del topic SNS
        Protocol: sqs
        Endpoint: !GetAtt SQSPE.Arn  # Usamos el ARN de la cola SQS directamente

    SNSSubscriptionCL:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref SNSCL  # Utilizando la referencia del topic SNS
        Protocol: sqs
        Endpoint: !GetAtt SQSCL.Arn  # Usamos el ARN de la cola SQS directamente

plugins:
  - serverless-offline
